### ISSUE TITLE
Weird warning during COUNT queries

### ISSUE THREAD

**Issue by moustaki** [njh/redstore#47]
To reproduce, start redstore, then issue the following SPARQL query:

  SELECT (COUNT(?s) as ?count) WHERE { ?s rdf:type _:o}

The following warning appears:

  Variable $$agg$$0 was used but is not bound in the query

This seems to happen for all queries including a COUNT as a selected variable.

**Comment by njh** [comment]
Looks like the warning came from:
https://github.com/dajobe/rasqal/blob/38391bf4b9f9ae9557b2810a18362c16d82f56ad/src/rasqal_query_transform.c#L1233

Warning level:
RASQAL_WARNING_LEVEL_SELECTED_NEVER_BOUND = 
RASQAL_WARNING_LEVEL_MAYBE_ERROR = 10

Changing the default warning level to 9 might have just turned off al warnings.
