### ISSUE TITLE
Most browsers will default to ISO-8859-1 instead UTF-8 charset

### ISSUE THREAD

**Issue by vit1251** [njh/redstore#49]
I think most browsers will default to ISO-8859-1, if no character set is specified.
Would be a good idea to add a UTF-8 character set header to the HTML pages.

**Comment by njh** [comment]
Thanks. Fixed in 7004d9d0986128da50ae9524bac7924b41ce2c2f

**Comment by vit1251** [comment]
No problem. But 5 year late ;-)

**Comment by njh** [comment]
Better late than never?

**Comment by vit1251** [comment]
TEMPORE QUAEDAM MAGNA FIUNT, NON SUMMA

**Comment by vit1251** [comment]
In any case tahnks.
