### ISSUE TITLE
404 errors accessing aelius.com

### ISSUE THREAD

**Issue by Hibou57** [njh/redstore#55]
The first time I followed the link http://www.aelius.com/njh/redstore/ with my browser, I got a 404 error page. Surprisingly, after I tried to go the the domain’s root, getting back to the former URL, I did not get a 404 error again.

Fetching http://www.aelius.com/njh/redstore/redstore-0.5.4.tar.gz with `curl` always return a 404 error document, while it works when downloaded with my browser. Trying again with `curl` I tried to add a user agent string and then a referrer string, but still does not work.

The website behave strangely.

**Comment by njh** [comment]
Hello,

I moved aelius.com to HTTPS a while go and turned on [HTTP Strict Transport Security](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).

So I guess what is happening is that the first time you access the page on http:// it is not redirecting you, but after visiting the homepage, HSTS is enabled and the browser knows not to attempt plain HTTP at all.

For now you can just change URLs to https:// with curl, but I will try and fix the broken redirects.

nick.

**Comment by njh** [comment]
I have now fixed this with with some mod_rewrite magic.
