### ISSUE TITLE
[proposal] Create a new store when it does not exist and `-n` is not given

### ISSUE THREAD

**Issue by Hibou57** [njh/redstore#57]
Starting Redstore with `redstore -s sqlite foo.db` where `foo.db` does not exist and trying to insert triples, ends with an internal server error (error 500), due to missing tables (which can’t be there).

As a work‑around, a script starting Redstore can check the file exist and it it does not, add the `-n` option. I just though this may avoid surprise if Redstore did it ifself.

**Comment by njh** [comment]
Hi,

I tried to make RedStore as thin as possible and ensure that as much of the the RDF/TripleStore functionality is in the Redland libraries as possible.

This behaviour of not creating the store automatically is Redland behaviour - you can experience the same thing with [rdfproc](http://librdf.org/utils/rdfproc.html) - see the -n option there.

But I agree it isn't ideal.

nick.

**Comment by Hibou57** [comment]
I understand. Don’t mind closing this issue, that’s just a detail as this can be workaround with no pain.

**Comment by njh** [comment]
Ok, I will close this one.
